version: '3'
services:
  frontend:
    build: ./ui/
    ports:
      - "80:80"
  backend:
    build: .
    ports:
     - "5000:5000"
  db:
    image: postgres:9.3 
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: test123
    volumes:
      - ~/postgres/data:/var/lib/postgresql/data